name: CI/CD Pipeline - Backend

on:
  push:
    branches-ignore:
      - master
    paths:
      - "backend/**"
  pull_request:
    branches-ignore:
      - master
    paths:
      - "backend/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run CSpell
        run: npx cspell "**"
      - name: Run Linting
        run: npx eslint
      - name: Run Tests
        run: cd ./backend && npm run test
