name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run CSpell
        run: npx cspell "**"
      - name: Run Linting
        run: npx eslint
      - name: Run Tests Backend
        run: cd ./backend && npm run test
      - name: Run Tests Frontend
        run: cd ./frontend && npm run test
